<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>TS_HappyPath</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>db0a3cb8-d2d0-4af6-807c-74657f7104df</testSuiteGuid>
   <testCaseLink>
      <guid>4b0760d9-53d7-4c21-a7cb-97e652d5e950</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Happy Path/00-Login/UW_LogIn_TST</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>f5646b65-7dbd-4e3d-bed6-a11bdf03ee89</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Happy Path/02-CreateSubmission/CreateSubmission</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a8e15a9b-ae28-40a4-8899-065f45c26229</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Happy Path/03-Applicant/01-Name and Address</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>5694d4ab-d509-4847-810f-e8d8c6f15680</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c494cd10-e2c1-4029-8e3a-28af92c0853d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>33147d7a-a533-458c-90e7-f111380277f9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d0243eb7-4320-4119-8da8-48b72d3e222f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4cc5b9a5-6e85-4917-aaf6-c25e8e7a40f6</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>6a7a2330-180f-4464-9033-8a4d771e4e30</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Happy Path/03-Applicant/02-Business Details</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>afe8ff90-46cf-4784-ba09-c7bd19dfae8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50ebadc8-a2d9-44c1-821c-94126fdecccd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f3e501ed-8167-44e7-9361-00783f8a8dc1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>998c7eca-4fcb-46a4-859c-e119ad722051</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe64a879-6862-4996-8a85-cecb08c7043c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cf073fe3-2194-4beb-b3f3-83e6e825a03d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fbd87b01-2c66-4262-901f-3dfae7419ddd</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7ba7d60e-f7e6-462a-bbad-e5c44ed9e63c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>560690e1-bac8-4926-9941-b7665cf70a0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>824e6b94-b8d3-48a0-808c-ae3b7f163ff7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>861417b4-9d3a-4334-a49c-486230762e11</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Happy Path/03-Applicant/03-Filings Information</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d51138b9-a563-4c96-a70f-ffc1ab5718a8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bfa99251-8132-4630-a100-704969e6c45c</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e9ccc308-7997-4de6-8d64-1ab13292a705</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Happy Path/03-Applicant/04-Additional Interest</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8f775449-1087-4dca-8abd-abf9595f731f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c8739b00-0268-43ce-94f8-7e7b417e3052</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>36daa7b3-a874-4bfc-89fc-04b07ea958b2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0d149eff-3b0b-419d-8951-cafe68cc7cca</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0f4446b9-9cd3-44b2-ae4d-761e8ee10fa4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>493d0fab-d975-4c22-a1f6-8dd3443fac96</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>339008f9-3e90-4de6-bc71-337f0d162abb</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Happy Path/04-Broker/Broker</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>088eb07a-43f4-4239-bd8b-67db863c33d6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f87e41c3-0be6-4d2c-8c15-ef8acf794cc9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6d29bcb1-856e-44d0-b77b-99cc95404d3e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2dc0aed3-0e16-4ff5-925d-fc38168cbf3d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f00342d-be51-4cf1-9439-e41237941a35</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0c41a5a1-1d39-4d96-afe8-086c0efab7b5</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>19bf1a2d-4b57-4d86-a5b4-413790acf070</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Happy Path/05-Limits/Limits</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f55e3aae-3e87-4881-ac80-9efe1be8c422</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>66b2a29b-3809-47e0-b27f-63b5bc4eb51f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e4f74bff-1532-4b64-b084-ff145f5050a9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>01e6b283-a849-4e2c-8508-8ee3d37c2bf5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>42bc4b2f-be63-4784-b326-1c9a2a90252c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>19ab5dfb-e8b0-4a44-8951-e251c72ab5b4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2c29e755-cb79-4755-bfdc-7fb1f25c7e26</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0bdfed81-f6bd-4626-bea1-e230de53cb8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>319e1403-7b84-42dd-ada3-6bfbeb7cac9e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>222eeb58-2f46-4de2-b987-8f5515ab1665</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f534ee0e-acc9-4641-b7b4-39c9344aa286</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Happy Path/06-Vehicle/Vehicles</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>cc5335b7-55b3-4868-9c23-a03fe95e3ad1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ddef9383-3365-42a1-bcdf-96befd571129</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a54bea02-73b8-4ca5-ae1d-005df37eb870</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dfe905e6-2f82-4979-8b16-5d1e674dfd5e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fd009e11-76a7-4f9c-87ea-30326f260d64</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6fe42613-d025-4380-9221-ccfdb2d9ee1d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>83a43d4a-85ee-419a-897e-3204a78c1b16</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3cd28bd6-14b8-465c-8ee5-df8583938732</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>86900366-b4a2-48f1-981f-da3d8be46e0b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ef4e870c-5bd3-4e0f-9330-71f9a7e4a50c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>43b07f77-e68d-458e-8c91-2847487d29b9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>45004b77-a78c-4715-892d-39a574b70f01</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Happy Path/07-Driver/Drivers</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8bbed0db-78c9-4c0c-a782-094f9e08a922</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ed1a9063-4898-45f0-95ab-cd5d2336df51</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91cb586a-1a68-41d2-bb2a-4169dca95912</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dc6c1c53-21e3-4010-95eb-ef431d2f74e7</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>4cc89f24-7089-4389-83b9-4344a058678b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Happy Path/08-Historical Coverage/Historical Coverage</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>e6222ab4-58a8-4dd7-b5f5-bd5a9a5ee275</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8a15053a-d3dd-4820-9195-f0ff188abd3c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f1cdfd14-aaf5-4c1d-9a3d-50a274f08768</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63f2582b-9ed5-42f0-b189-4555bf72d613</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3c5e87a9-0986-4c35-9bda-f5295ddf474f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ce5a68f1-0642-499a-961d-b865418f4795</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>79d4bc7b-56ac-41c2-8706-3df938efad8e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>81ba0fa3-ee1c-48c7-8c50-c977971ca2cd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Happy Path/09-Claims History/Claims History</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4e81d763-e0bc-404d-988d-99e2800494b0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>240a1614-b9ab-4465-8b05-367366ded4e0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2d6bf623-f926-49e4-8e0e-a36fc28556b5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a0ea41ce-882f-41f8-8271-c3a12620b6df</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>16e9809c-f1af-44c4-aaf0-d0143c14511f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>117ae868-a846-408e-b1b6-637501d658d5</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a9cb1ec3-a8e1-4378-accc-ceddd04e1c69</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>14735f18-782d-4b2d-91ab-98c66632bf40</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>309c4a25-cec0-4daf-8a41-eb8ecdca0be2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Happy Path/10-Risk Specifics/01-Destination Information</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8b2cd106-83a2-4c0a-8ddc-a7be2f496ce8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Happy Path/10-Risk Specifics/02-Driver Information</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d826be28-2b4a-47ed-abe5-a17c2764bdc6</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Happy Path/10-Risk Specifics/03-DOT Information</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>88a29623-5599-4a55-85fd-c1c2ee25b066</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Happy Path/10-Risk Specifics/04-Maintenance or Safety</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>888f70df-a21f-488e-a236-1513ba6d8498</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Happy Path/10-Risk Specifics/05-Gen Liab and Cargo</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8b21a098-7d28-4700-b5d8-e53cd94c125b</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2579cf9b-7f13-4ea4-a7ae-0a7c9e50800b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Happy Path/10-Risk Specifics/06-Underwriting Questions</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a6b25d21-9694-4296-9caa-4d098aef2524</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Happy Path/11-Quote Option/01_Quote Option</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
