<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>04-dtxt_TotalAmountDueFullPay</name>
   <tag></tag>
   <elementGuidId>fa076c87-a00b-406f-b66c-1c735bb57a29</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@formcontrolname='totalAmounDueFull']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@formcontrolname='totalAmounDueFull']</value>
   </webElementProperties>
</WebElementEntity>
