<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>09-dtxt_InstallmentFee</name>
   <tag></tag>
   <elementGuidId>feb0c1b6-b789-42b2-928a-64d6c5bcad1a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@formcontrolname='installmentFee']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@formcontrolname='installmentFee']</value>
   </webElementProperties>
</WebElementEntity>
