<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>05-toggle_Volunteers</name>
   <tag></tag>
   <elementGuidId>565d3569-8983-4e8d-8b34-301241f83313</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='areVolunteersUsedInBusiness']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='areVolunteersUsedInBusiness']</value>
   </webElementProperties>
</WebElementEntity>
