<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>07-toggle_HireFromOthers</name>
   <tag></tag>
   <elementGuidId>b63dbe8c-a10f-4d3c-b857-9d5ad6c0d594</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='isHiringFromOthers']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='isHiringFromOthers']</value>
   </webElementProperties>
</WebElementEntity>
