<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>08-txt_AnnualCost_1</name>
   <tag></tag>
   <elementGuidId>dfd47bc5-3d4d-4d48-9bfa-fc77706b94e5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='annualCostOfHireFromOthersForUse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='annualCostOfHireFromOthersForUse']</value>
   </webElementProperties>
</WebElementEntity>
