<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>11-toggle_LeasingToOthers</name>
   <tag></tag>
   <elementGuidId>15b21c78-7df7-4b49-b27a-f11a8b5c1134</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='isLeasingToOthers']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='isLeasingToOthers']</value>
   </webElementProperties>
</WebElementEntity>
