<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>12-txt_AnnualIncome_1</name>
   <tag></tag>
   <elementGuidId>c93deb9b-fd68-40ce-b220-c860423ab51a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='annualIncomeDerivedUse']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='annualIncomeDerivedUse']</value>
   </webElementProperties>
</WebElementEntity>
