<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>13-toggle_LeaseDriver</name>
   <tag></tag>
   <elementGuidId>e0dda603-14e7-4d05-bcde-e69a1ea56145</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='isLeasingToOthersWithoutDriver']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='isLeasingToOthersWithoutDriver']</value>
   </webElementProperties>
</WebElementEntity>
