<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>14-txt_AnnualIncome_2</name>
   <tag></tag>
   <elementGuidId>34d7a239-1d53-4f93-8064-c489b0cb5c5f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='annualIncomeDerivedLease']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='annualIncomeDerivedLease']</value>
   </webElementProperties>
</WebElementEntity>
