<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>15-toggle_AssumedLiability</name>
   <tag></tag>
   <elementGuidId>a2a5c662-adba-4be1-ab1f-fac44706deae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='isThereAssumedLiabilityByContract']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='isThereAssumedLiabilityByContract']</value>
   </webElementProperties>
</WebElementEntity>
