<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>16-toggle_VehicleHome</name>
   <tag></tag>
   <elementGuidId>ab2f325d-29c8-4f70-816f-cad01dc256fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='doDriversTakeVehiclesHome']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='doDriversTakeVehiclesHome']</value>
   </webElementProperties>
</WebElementEntity>
