<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>01-toggle_2_CurrentlyPlace</name>
   <tag></tag>
   <elementGuidId>33649434-b47a-48d3-85f5-e37b9ac9cdc0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//span[@id='isInPlace'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[@id='isInPlace'])[2]</value>
   </webElementProperties>
</WebElementEntity>
