<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>01-dtxt_RiskMngmt_AL</name>
   <tag></tag>
   <elementGuidId>bb62ef1a-4323-4feb-9c5b-3d687d6a210e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@formcontrolname='riskMgrFeeAL']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@formcontrolname='riskMgrFeeAL']</value>
   </webElementProperties>
</WebElementEntity>
