<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>01-txt_LossRunDate</name>
   <tag></tag>
   <elementGuidId>2315b11c-5e62-4c1d-888a-006f2f459087</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@placeholder='mm/dd/yyyy'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@placeholder='mm/dd/yyyy'])[1]</value>
   </webElementProperties>
</WebElementEntity>
