<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>06-dropDown_MedicalPayment</name>
   <tag></tag>
   <elementGuidId>6b145d22-5247-4bd9-8480-4f16049efdc7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[contains(@id,'medPayLimitSymbolId')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[contains(@id,'medPayLimitSymbolId')]</value>
   </webElementProperties>
</WebElementEntity>
