<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>08-dropDown_LiabilityDed</name>
   <tag></tag>
   <elementGuidId>09a87ac4-cd3a-4cc5-bda6-204e85a79052</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[contains(@id,'liabilityDeductibleSymbolId')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[contains(@id,'liabilityDeductibleSymbolId')]</value>
   </webElementProperties>
</WebElementEntity>
