<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>12-dropDown_Cargo</name>
   <tag></tag>
   <elementGuidId>6618f72e-9b6a-430e-9ab7-b07664dc3615</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[contains(@id,'cargoLimitSymbolId')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[contains(@id,'cargoLimitSymbolId')]</value>
   </webElementProperties>
</WebElementEntity>
