<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>10-txt_LossRunDate</name>
   <tag></tag>
   <elementGuidId>3788cade-5e9f-4eb1-a074-a4f41e6c2a59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@placeholder='mm/dd/yyyy'])[11]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@placeholder='mm/dd/yyyy'])[11]</value>
   </webElementProperties>
</WebElementEntity>
