<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>16-txt_GrossRevenues</name>
   <tag></tag>
   <elementGuidId>984536cf-3e6d-4b9b-831d-e8076f78328f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//tbody/tr[1]/td[2]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//tbody/tr[1]/td[2]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
