<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>18-txt_NoOneWayTrips</name>
   <tag></tag>
   <elementGuidId>8f04420d-06eb-47bf-a414-caceff80aedf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body[1]/app-main-sidebar-layout[1]/div[1]/main[1]/div[1]/app-submission-details[1]/app-historical-coverage[1]/div[1]/app-historical-coverage-section[1]/div[1]/div[2]/div[1]/form[1]/app-projection-figures-chart[1]/form[1]/div[1]/table[1]/tbody[1]/tr[3]/td[2]/input[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body[1]/app-main-sidebar-layout[1]/div[1]/main[1]/div[1]/app-submission-details[1]/app-historical-coverage[1]/div[1]/app-historical-coverage-section[1]/div[1]/div[2]/div[1]/form[1]/app-projection-figures-chart[1]/form[1]/div[1]/table[1]/tbody[1]/tr[3]/td[2]/input[1]</value>
   </webElementProperties>
</WebElementEntity>
