<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>04-multiDropDown_Maintenance</name>
   <tag></tag>
   <elementGuidId>c4bcbd76-4cba-4641-b6c5-9c812200941a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//span[@tabindex='-1'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[@tabindex='-1'])[2]</value>
   </webElementProperties>
</WebElementEntity>
