<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>06-toggle_MaintenanceVin</name>
   <tag></tag>
   <elementGuidId>ce332177-874b-4ff5-be3c-6bcf66e3a833</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='provideCompleteMaintenanceOnVehicles']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='provideCompleteMaintenanceOnVehicles']</value>
   </webElementProperties>
</WebElementEntity>
