<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>08-AccidentReview</name>
   <tag></tag>
   <elementGuidId>5dd983f0-d362-4b83-a988-2618fcee9297</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='areAccidentFilesAvailableForReview']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='areAccidentFilesAvailableForReview']</value>
   </webElementProperties>
</WebElementEntity>
