<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>02-dtxt_PhysicalDamage_Premium</name>
   <tag></tag>
   <elementGuidId>013aa640-59ec-4527-90db-2c9e5ff00735</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='pdPremiumInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='pdPremiumInput']</value>
   </webElementProperties>
</WebElementEntity>
