<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>06-dropDown_MedicalPayment</name>
   <tag></tag>
   <elementGuidId>22177b1f-0923-47d6-89c4-b366da344c2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[contains(@id,'medPayLimitId')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[contains(@id,'medPayLimitId')]</value>
   </webElementProperties>
</WebElementEntity>
