<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>02-checkBox_WoF</name>
   <tag></tag>
   <elementGuidId>c682a15b-bfb0-4b5f-bae2-42ef9386141e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@formcontrolname='isWaiverOfSubrogation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@formcontrolname='isWaiverOfSubrogation']</value>
   </webElementProperties>
</WebElementEntity>
