<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>01-dropDown_SubmissionSpecialist</name>
   <tag></tag>
   <elementGuidId>49c70471-36ea-4b8d-849b-946c5ed21604</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id='submissionSpecialistUserId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='submissionSpecialistUserId']</value>
   </webElementProperties>
</WebElementEntity>
