<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>12-dropDown_TypeOfBusiness</name>
   <tag></tag>
   <elementGuidId>a58ff8e4-d970-4eac-be29-305512a756cf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id='typeOfBusinessDropdown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='typeOfBusinessDropdown']</value>
   </webElementProperties>
</WebElementEntity>
