<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>01-toggle_ProvideCompensation</name>
   <tag></tag>
   <elementGuidId>1f650a07-2ed8-48a2-b6c4-af8d07e8e390</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='areWorkersCompensationProvided']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='areWorkersCompensationProvided']</value>
   </webElementProperties>
</WebElementEntity>
