<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>03-txt_RiskPlanExplanation</name>
   <tag></tag>
   <elementGuidId>9ac1823f-41fd-448d-9e04-66e7ebfa9034</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@id='obtainedThruAssignedRiskPlanExplanation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[@id='obtainedThruAssignedRiskPlanExplanation']</value>
   </webElementProperties>
</WebElementEntity>
