<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>05-toggle_FillingBankruptcy</name>
   <tag></tag>
   <elementGuidId>999b5a8f-0ef5-48de-b348-1eebc3f34ca5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='hasFiledForBankruptcy']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='hasFiledForBankruptcy']</value>
   </webElementProperties>
</WebElementEntity>
