<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>05-txt_BankruptcyExplanation</name>
   <tag></tag>
   <elementGuidId>0ce3279d-be34-4312-9ae6-72c24e255eed</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@id='filingForBankruptcyExplanation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[@id='filingForBankruptcyExplanation']</value>
   </webElementProperties>
</WebElementEntity>
