<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>06-toggle_AuthSuspended</name>
   <tag></tag>
   <elementGuidId>93f7daf5-1907-47a7-9338-140b67884731</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='hasOperatingAuthoritySuspended']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='hasOperatingAuthoritySuspended']</value>
   </webElementProperties>
</WebElementEntity>
