<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>06-txt_SuspensionExplanation</name>
   <tag></tag>
   <elementGuidId>0b0a40a7-1422-4637-bfd4-16253a1d61fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@id='suspensionExplanation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[@id='suspensionExplanation']</value>
   </webElementProperties>
</WebElementEntity>
