<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>07-toggle_Covid19</name>
   <tag></tag>
   <elementGuidId>26ec9625-300e-43f5-ab32-4ac2c1183503</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='hasVehicleCountBeenAffectedByCovid19']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='hasVehicleCountBeenAffectedByCovid19']</value>
   </webElementProperties>
</WebElementEntity>
