<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>01-toggle_CarryGenLiab</name>
   <tag></tag>
   <elementGuidId>52ceb9cf-d9d7-4b9e-a245-7b6fde31f6de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='contractuallyRequiredToCarryGeneralLiabilityInsurance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='contractuallyRequiredToCarryGeneralLiabilityInsurance']</value>
   </webElementProperties>
</WebElementEntity>
