<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>06-toggle_LeasingSpace</name>
   <tag></tag>
   <elementGuidId>02541275-0d26-4d79-b8d4-d206c7ec09d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='anyLeasingSpaceToOthers']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='anyLeasingSpaceToOthers']</value>
   </webElementProperties>
</WebElementEntity>
