<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>00-lbl-SubmissionNumber</name>
   <tag></tag>
   <elementGuidId>b9d225c2-ed75-4def-a3b4-702e88708507</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//h6[@class='field-text'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//h6[@class='field-text'])[2]</value>
   </webElementProperties>
</WebElementEntity>
