<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>00-lbl_SubmissionNumber</name>
   <tag></tag>
   <elementGuidId>25ac5bee-0807-4bb4-b9d5-8ced0bca7069</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//label[@class='field-text'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//label[@class='field-text'])[2]</value>
   </webElementProperties>
</WebElementEntity>
