<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>06_dropDown_UWAcctCategory</name>
   <tag></tag>
   <elementGuidId>538fbc2d-a196-47e6-9bef-013a29527ca6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@id='accountCategoryUWDropdown']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@id='accountCategoryUWDropdown']</value>
   </webElementProperties>
</WebElementEntity>
