<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>01-toggle_RequiredCarryCargo</name>
   <tag></tag>
   <elementGuidId>fa08f1ee-f91c-477b-858c-52b5f76c290a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='areRequiredToCarryCargoInsurance']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='areRequiredToCarryCargoInsurance']</value>
   </webElementProperties>
</WebElementEntity>
