<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>02-toggle_RequireRefBreakdown</name>
   <tag></tag>
   <elementGuidId>b49f0f63-bed3-464f-a89c-6c23d83adf14</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='requireRefrigerationBreakdownCoverage']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='requireRefrigerationBreakdownCoverage']</value>
   </webElementProperties>
</WebElementEntity>
