<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>04-toggle_RefUnits</name>
   <tag></tag>
   <elementGuidId>913c9d95-6408-45de-a376-fbe82fb2d9a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='haveRefrigeratedUnits']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='haveRefrigeratedUnits']</value>
   </webElementProperties>
</WebElementEntity>
