<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>05-txt_Explain</name>
   <tag></tag>
   <elementGuidId>dbdfff12-0654-4a36-ac15-4c504b54758a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//textarea[@id='areCommoditiesStoredInTruckOvernightExplain']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//textarea[@id='areCommoditiesStoredInTruckOvernightExplain']</value>
   </webElementProperties>
</WebElementEntity>
