<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>01-toggle_UnsafeDriving</name>
   <tag></tag>
   <elementGuidId>2013a106-fad5-49ff-abef-4d72dc1bef5a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='isUnsafeDrivingChecked']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='isUnsafeDrivingChecked']</value>
   </webElementProperties>
</WebElementEntity>
