<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>04-toggle_ControlledSubstance</name>
   <tag></tag>
   <elementGuidId>c2ec6154-c177-4fd0-b1e4-737a198f1e9b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='isControlledSubstanceChecked']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='isControlledSubstanceChecked']</value>
   </webElementProperties>
</WebElementEntity>
