<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>05-toggle_VehicleMaintenance</name>
   <tag></tag>
   <elementGuidId>882543a8-3f89-44a9-82d4-62101c602be5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='isVehicleMaintenanceChecked']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='isVehicleMaintenanceChecked']</value>
   </webElementProperties>
</WebElementEntity>
