<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>06-datePicker_EffectiveDate</name>
   <tag></tag>
   <elementGuidId>6e6d208d-46bc-4bac-84cf-4278f9a1108b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[contains(@placeholder,'mm/dd/yyyy')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[contains(@placeholder,'mm/dd/yyyy')])[1]</value>
   </webElementProperties>
</WebElementEntity>
