<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>08-toggle_Waiver</name>
   <tag></tag>
   <elementGuidId>6c3ca665-337f-43cb-b246-ca88b8e70574</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='isWaiverOfSubrogation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='isWaiverOfSubrogation']</value>
   </webElementProperties>
</WebElementEntity>
