<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>11-toggle_GenLiab</name>
   <tag></tag>
   <elementGuidId>9bc83fcc-b8ca-4d31-bf61-4eb71f76e7ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='isGeneralLiability']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='isGeneralLiability']</value>
   </webElementProperties>
</WebElementEntity>
