<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>16-toggle_Cargo</name>
   <tag></tag>
   <elementGuidId>71c23c7e-bae7-43d7-b45a-70327ba26c1d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(@id,'hasCoverageCargo')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(@id,'hasCoverageCargo')]</value>
   </webElementProperties>
</WebElementEntity>
