<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>09-txt-YCDE</name>
   <tag></tag>
   <elementGuidId>165b37b1-1cdc-4d3a-afd6-7f6e1a922837</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='yrsCommDrivingExp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='yrsCommDrivingExp']</value>
   </webElementProperties>
</WebElementEntity>
