<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>12-txt_IncidentDate</name>
   <tag></tag>
   <elementGuidId>6f2ba0e8-3c72-46ad-8a89-969c4c65ca8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//input[@placeholder='mm/dd/yyyy'])[5]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//input[@placeholder='mm/dd/yyyy'])[5]</value>
   </webElementProperties>
</WebElementEntity>
