<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>01-toggle_1_CurrentlyPlace</name>
   <tag></tag>
   <elementGuidId>5cb38f74-d9cd-45b5-b6e0-2bf8a9164d2e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//span[@id='isInPlace'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[@id='isInPlace'])[1]</value>
   </webElementProperties>
</WebElementEntity>
