<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>04-dropDown_Retailer</name>
   <tag></tag>
   <elementGuidId>d54f03ef-62b5-452b-b041-0ba578b76d11</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[contains(@formcontrolname,'subAgencyId')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[contains(@formcontrolname,'subAgencyId')]</value>
   </webElementProperties>
</WebElementEntity>
