<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>05-dropDown_AgentName</name>
   <tag></tag>
   <elementGuidId>88c16c99-5251-46be-8a20-10ef9691c53c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[contains(@formcontrolname,'subAgentId')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[contains(@formcontrolname,'subAgentId')]</value>
   </webElementProperties>
</WebElementEntity>
