<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>02-toggle_StayIntrastate</name>
   <tag></tag>
   <elementGuidId>07d962be-6146-4361-b859-18f569a463d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='doesApplicantPlanToStayInterstate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='doesApplicantPlanToStayInterstate']</value>
   </webElementProperties>
</WebElementEntity>
