<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>06-dropDown_Chameleon</name>
   <tag></tag>
   <elementGuidId>4d74c675-f2ca-48a9-9387-dc5b9059cdea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body/app-main-sidebar-layout[1]/div[1]/main[1]/div[1]/app-submission-details[1]/app-risk-specifics[1]/app-dot-information[1]/div[1]/div[1]/div[2]/form[1]/div[2]/div[3]/div[1]/select[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body/app-main-sidebar-layout[1]/div[1]/main[1]/div[1]/app-submission-details[1]/app-risk-specifics[1]/app-dot-information[1]/div[1]/div[1]/div[2]/form[1]/div[2]/div[3]/div[1]/select[1]</value>
   </webElementProperties>
</WebElementEntity>
