<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>07-dropDown_SaferRating</name>
   <tag></tag>
   <elementGuidId>81325772-6081-4e56-a474-27d34da923b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@formcontrolname='currentSaferRating']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//select[@formcontrolname='currentSaferRating']</value>
   </webElementProperties>
</WebElementEntity>
