<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>08-dropDown_CabRating</name>
   <tag></tag>
   <elementGuidId>d9558dc9-c073-4d84-838b-bd9b61cc3502</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//body/app-main-sidebar-layout[1]/div[1]/main[1]/div[1]/app-submission-details[1]/app-risk-specifics[1]/app-dot-information[1]/div[1]/div[1]/div[2]/form[1]/div[3]/div[2]/div[1]/select[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//body/app-main-sidebar-layout[1]/div[1]/main[1]/div[1]/app-submission-details[1]/app-risk-specifics[1]/app-dot-information[1]/div[1]/div[1]/div[2]/form[1]/div[3]/div[2]/div[1]/select[1]</value>
   </webElementProperties>
</WebElementEntity>
