<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>10-txt_HowMany</name>
   <tag></tag>
   <elementGuidId>ab9f7603-9f22-4b66-bc35-ba75123c14b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='numberOfPolicyLevelAccidents']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='numberOfPolicyLevelAccidents']</value>
   </webElementProperties>
</WebElementEntity>
