<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>01-multiDropDown_SafetyDevice_One</name>
   <tag></tag>
   <elementGuidId>f70ba973-19f7-465a-88c2-fcb2cb0bfee8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[contains(@tabindex,'-1')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[contains(@tabindex,'-1')]</value>
   </webElementProperties>
</WebElementEntity>
