<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>07-txt_51-200</name>
   <tag></tag>
   <elementGuidId>5e816d09-1307-41c2-8b26-707672ad0ffc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[@id='fiftyOneToTwoHundredMilesInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[@id='fiftyOneToTwoHundredMilesInput']</value>
   </webElementProperties>
</WebElementEntity>
