<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>10-toggle_NYC</name>
   <tag></tag>
   <elementGuidId>266bd4b6-4bb1-4bff-9a91-cf9b25a280fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='anyNyc5BoroughsExposure']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='anyNyc5BoroughsExposure']</value>
   </webElementProperties>
</WebElementEntity>
