<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>07-toggle_AllowedOperatePast</name>
   <tag></tag>
   <elementGuidId>dd3c5c13-3c68-4ce1-9ca8-b0d925489f60</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='isOthersAllowedToOperatePast']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='isOthersAllowedToOperatePast']</value>
   </webElementProperties>
</WebElementEntity>
