<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>09_toggle_DOTNumber</name>
   <tag></tag>
   <elementGuidId>d13f47a5-ba0d-43ff-9d7d-daf26dcefc8c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='isDifferentUSDOTNumberLastFiveYears']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='isDifferentUSDOTNumberLastFiveYears']</value>
   </webElementProperties>
</WebElementEntity>
