<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>10_txt_DOT</name>
   <tag></tag>
   <elementGuidId>d7971147-e075-4364-8ce5-3567a8ecdccf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//input[contains(@formcontrolname,'dotNumberLastFiveYearsDetail')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//input[contains(@formcontrolname,'dotNumberLastFiveYearsDetail')]</value>
   </webElementProperties>
</WebElementEntity>
