<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>03-toggle_AgreeReport</name>
   <tag></tag>
   <elementGuidId>41a6a045-f1cc-4dff-bef7-7d0b1a5f793c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//span[@id='isAgreedToReportAllDriversToRivington']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//span[@id='isAgreedToReportAllDriversToRivington']</value>
   </webElementProperties>
</WebElementEntity>
