<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>10-multiDropDown_DriverTraining</name>
   <tag></tag>
   <elementGuidId>0d419b85-efe6-4fb8-b6fa-6647f176033d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>(//span[@tabindex='-1'])[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>(//span[@tabindex='-1'])[2]</value>
   </webElementProperties>
</WebElementEntity>
